// Code generated by counterfeiter. DO NOT EDIT.
package signaturefakes

import (
	"sync"

	"github.com/google/go-containerregistry/pkg/name"
	"github.com/k14s/imgpkg/pkg/imgpkg/imageset"
	"github.com/k14s/imgpkg/pkg/imgpkg/signature"
)

type FakeFinder struct {
	SignatureStub        func(name.Digest) (imageset.UnprocessedImageRef, error)
	signatureMutex       sync.RWMutex
	signatureArgsForCall []struct {
		arg1 name.Digest
	}
	signatureReturns struct {
		result1 imageset.UnprocessedImageRef
		result2 error
	}
	signatureReturnsOnCall map[int]struct {
		result1 imageset.UnprocessedImageRef
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeFinder) Signature(arg1 name.Digest) (imageset.UnprocessedImageRef, error) {
	fake.signatureMutex.Lock()
	ret, specificReturn := fake.signatureReturnsOnCall[len(fake.signatureArgsForCall)]
	fake.signatureArgsForCall = append(fake.signatureArgsForCall, struct {
		arg1 name.Digest
	}{arg1})
	stub := fake.SignatureStub
	fakeReturns := fake.signatureReturns
	fake.recordInvocation("Signature", []interface{}{arg1})
	fake.signatureMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeFinder) SignatureCallCount() int {
	fake.signatureMutex.RLock()
	defer fake.signatureMutex.RUnlock()
	return len(fake.signatureArgsForCall)
}

func (fake *FakeFinder) SignatureCalls(stub func(name.Digest) (imageset.UnprocessedImageRef, error)) {
	fake.signatureMutex.Lock()
	defer fake.signatureMutex.Unlock()
	fake.SignatureStub = stub
}

func (fake *FakeFinder) SignatureArgsForCall(i int) name.Digest {
	fake.signatureMutex.RLock()
	defer fake.signatureMutex.RUnlock()
	argsForCall := fake.signatureArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeFinder) SignatureReturns(result1 imageset.UnprocessedImageRef, result2 error) {
	fake.signatureMutex.Lock()
	defer fake.signatureMutex.Unlock()
	fake.SignatureStub = nil
	fake.signatureReturns = struct {
		result1 imageset.UnprocessedImageRef
		result2 error
	}{result1, result2}
}

func (fake *FakeFinder) SignatureReturnsOnCall(i int, result1 imageset.UnprocessedImageRef, result2 error) {
	fake.signatureMutex.Lock()
	defer fake.signatureMutex.Unlock()
	fake.SignatureStub = nil
	if fake.signatureReturnsOnCall == nil {
		fake.signatureReturnsOnCall = make(map[int]struct {
			result1 imageset.UnprocessedImageRef
			result2 error
		})
	}
	fake.signatureReturnsOnCall[i] = struct {
		result1 imageset.UnprocessedImageRef
		result2 error
	}{result1, result2}
}

func (fake *FakeFinder) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.signatureMutex.RLock()
	defer fake.signatureMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeFinder) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ signature.Finder = new(FakeFinder)
