// Code generated by counterfeiter. DO NOT EDIT.
package bundlefakes

import (
	"sync"

	"carvel.dev/imgpkg/pkg/imgpkg/bundle"
)

type FakeImageRefLocationsConfig struct {
	ConfigStub        func() (bundle.ImageLocationsConfig, error)
	configMutex       sync.RWMutex
	configArgsForCall []struct {
	}
	configReturns struct {
		result1 bundle.ImageLocationsConfig
		result2 error
	}
	configReturnsOnCall map[int]struct {
		result1 bundle.ImageLocationsConfig
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeImageRefLocationsConfig) Config() (bundle.ImageLocationsConfig, error) {
	fake.configMutex.Lock()
	ret, specificReturn := fake.configReturnsOnCall[len(fake.configArgsForCall)]
	fake.configArgsForCall = append(fake.configArgsForCall, struct {
	}{})
	stub := fake.ConfigStub
	fakeReturns := fake.configReturns
	fake.recordInvocation("Config", []interface{}{})
	fake.configMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeImageRefLocationsConfig) ConfigCallCount() int {
	fake.configMutex.RLock()
	defer fake.configMutex.RUnlock()
	return len(fake.configArgsForCall)
}

func (fake *FakeImageRefLocationsConfig) ConfigCalls(stub func() (bundle.ImageLocationsConfig, error)) {
	fake.configMutex.Lock()
	defer fake.configMutex.Unlock()
	fake.ConfigStub = stub
}

func (fake *FakeImageRefLocationsConfig) ConfigReturns(result1 bundle.ImageLocationsConfig, result2 error) {
	fake.configMutex.Lock()
	defer fake.configMutex.Unlock()
	fake.ConfigStub = nil
	fake.configReturns = struct {
		result1 bundle.ImageLocationsConfig
		result2 error
	}{result1, result2}
}

func (fake *FakeImageRefLocationsConfig) ConfigReturnsOnCall(i int, result1 bundle.ImageLocationsConfig, result2 error) {
	fake.configMutex.Lock()
	defer fake.configMutex.Unlock()
	fake.ConfigStub = nil
	if fake.configReturnsOnCall == nil {
		fake.configReturnsOnCall = make(map[int]struct {
			result1 bundle.ImageLocationsConfig
			result2 error
		})
	}
	fake.configReturnsOnCall[i] = struct {
		result1 bundle.ImageLocationsConfig
		result2 error
	}{result1, result2}
}

func (fake *FakeImageRefLocationsConfig) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeImageRefLocationsConfig) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ bundle.ImageRefLocationsConfig = new(FakeImageRefLocationsConfig)
