// Code generated by counterfeiter. DO NOT EDIT.
package bundlefakes

import (
	"sync"

	"github.com/k14s/imgpkg/pkg/imgpkg/bundle"
)

type FakeImagesLockLocationConfig struct {
	FetchStub        func() (bundle.ImageLocationsConfig, error)
	fetchMutex       sync.RWMutex
	fetchArgsForCall []struct {
	}
	fetchReturns struct {
		result1 bundle.ImageLocationsConfig
		result2 error
	}
	fetchReturnsOnCall map[int]struct {
		result1 bundle.ImageLocationsConfig
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeImagesLockLocationConfig) Config() (bundle.ImageLocationsConfig, error) {
	fake.fetchMutex.Lock()
	ret, specificReturn := fake.fetchReturnsOnCall[len(fake.fetchArgsForCall)]
	fake.fetchArgsForCall = append(fake.fetchArgsForCall, struct {
	}{})
	stub := fake.FetchStub
	fakeReturns := fake.fetchReturns
	fake.recordInvocation("Config", []interface{}{})
	fake.fetchMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeImagesLockLocationConfig) FetchCallCount() int {
	fake.fetchMutex.RLock()
	defer fake.fetchMutex.RUnlock()
	return len(fake.fetchArgsForCall)
}

func (fake *FakeImagesLockLocationConfig) FetchCalls(stub func() (bundle.ImageLocationsConfig, error)) {
	fake.fetchMutex.Lock()
	defer fake.fetchMutex.Unlock()
	fake.FetchStub = stub
}

func (fake *FakeImagesLockLocationConfig) FetchReturns(result1 bundle.ImageLocationsConfig, result2 error) {
	fake.fetchMutex.Lock()
	defer fake.fetchMutex.Unlock()
	fake.FetchStub = nil
	fake.fetchReturns = struct {
		result1 bundle.ImageLocationsConfig
		result2 error
	}{result1, result2}
}

func (fake *FakeImagesLockLocationConfig) FetchReturnsOnCall(i int, result1 bundle.ImageLocationsConfig, result2 error) {
	fake.fetchMutex.Lock()
	defer fake.fetchMutex.Unlock()
	fake.FetchStub = nil
	if fake.fetchReturnsOnCall == nil {
		fake.fetchReturnsOnCall = make(map[int]struct {
			result1 bundle.ImageLocationsConfig
			result2 error
		})
	}
	fake.fetchReturnsOnCall[i] = struct {
		result1 bundle.ImageLocationsConfig
		result2 error
	}{result1, result2}
}

func (fake *FakeImagesLockLocationConfig) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.fetchMutex.RLock()
	defer fake.fetchMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeImagesLockLocationConfig) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ bundle.ImageRefLocationsConfig = new(FakeImagesLockLocationConfig)
