version: "2"
linters:
  default: none
  enable:
    - goheader
    - revive
    - unused
    - staticcheck
    - govet
  settings:
    goheader:
      values:
        regexp:
          copyright-year: 20[0-9][0-9]
      template-path: code-header-template.txt
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new-from-rev: 04e4b4c2c70952cd00b89ec3ed781f4cd01c9803
