linters:
  enable:
    - goheader
    - revive
    - deadcode
    - unused
    - staticcheck
    - typecheck
    - structcheck
    - govet
  disable-all: true
# all available settings of specific linters
linters-settings:
  goheader:
    values:
      regexp:
        copyright-year: 202[0-1]
    template-path: code-header-template.txt
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false
  new-from-rev: 01ef727b5a403cf1df143adbf699aa0de2c765d9
