
# all available settings of specific linters
linters-settings:
  goheader:
    values:
      const:
        COMPANY: Copyright 2020 VMware, Inc.
      # regexp:
      
        # AUTHOR: .*@mycompany\.com
    template: |
     {{ COMPANY }}
     SPDX-License-Identifier: Apache-2.0
linters:
  enable:
    - goheader
  disable-all: true
