#!/bin/bash

set -u

docker volume create volume-to-use-when-locking > /dev/null

docker run --rm -v rw:/volume-to-use-when-locking ubuntu:21.04 /bin/bash -c "$(cat <<EOF
exec 3> /volume-to-use-when-locking/lock
if ! flock --timeout 1 --exclusive 3; then
 echo 'ERROR: gcloud crashed (OperationalError): database is locked'
 exit 1
fi

sleep 5
flock --unlock 3
cat <<OUTPUT
{
  "Secret": "fake.secret",
  "Username": "_dcgcloud_token"
}
OUTPUT
EOF
)"
