// Copyright 2024 The Carvel Authors.
// SPDX-License-Identifier: Apache-2.0

package e2e

import (
	"testing"

	"carvel.dev/imgpkg/test/helpers"
	uitest "github.com/cppforlife/go-cli-ui/ui/test"
	"github.com/stretchr/testify/require"
)

func TestTagList(t *testing.T) {
	env := helpers.BuildEnv(t)
	imgpkg := helpers.Imgpkg{T: t, L: helpers.Logger{}, ImgpkgPath: env.ImgpkgPath}
	defer env.Cleanup()

	out := imgpkg.Run([]string{"push", "--tty", "-i", env.Image + ":tag1", "-f", env.Assets.SimpleAppDir()})
	tag1Digest := helpers.ExtractDigest(t, out)

	out = imgpkg.Run([]string{"push", "--tty", "-i", env.Image + ":tag2", "-f", env.Assets.SimpleAppDir()})
	tag2Digest := helpers.ExtractDigest(t, out)

	out = imgpkg.Run([]string{"push", "--tty", "-i", env.Image + ":someautogeneratedtag.imgpkg", "-f", env.Assets.SimpleAppDir()})
	imgpkgTagDigest := helpers.ExtractDigest(t, out)

	expectedTags := map[string]string{"tag1": tag1Digest, "tag2": tag2Digest}

	{ // Without digests
		out := imgpkg.Run([]string{"tag", "list", "-i", env.Image, "--json"})
		resp := uitest.JSONUIFromBytes(t, []byte(out))

		for name := range expectedTags {
			var found bool
			for _, row := range resp.Tables[0].Rows {
				require.NotContains(t, ".imgpkg", row["name"])
				if row["name"] == name {
					found = true
					require.Equal(t, "", row["digest"])
					break
				}
			}
			require.Truef(t, found, "Expected to find tag '%s'", name)
		}
	}

	{ // With digests
		out := imgpkg.Run([]string{"tag", "list", "-i", env.Image, "--digests=true", "--json"})
		resp := uitest.JSONUIFromBytes(t, []byte(out))

		for name, digest := range expectedTags {
			var found bool
			for _, row := range resp.Tables[0].Rows {
				require.NotContains(t, ".imgpkg", row["name"])
				if row["name"] == name {
					found = true
					require.Equal(t, digest, row["digest"])
					break
				}
			}
			require.Truef(t, found, "Expected to find tag '%s'", name)
		}
	}

	expectedTags["someautogeneratedtag.imgpkg"] = imgpkgTagDigest

	{ // With .imgpkg internal tags and no digests
		out := imgpkg.Run([]string{"tag", "list", "--imgpkg-internal-tags", "-i", env.Image, "--json"})
		resp := uitest.JSONUIFromBytes(t, []byte(out))

		for name := range expectedTags {
			var found bool
			for _, row := range resp.Tables[0].Rows {
				if row["name"] == name {
					found = true
					require.Equal(t, "", row["digest"])
					break
				}
			}
			require.Truef(t, found, "Expected to find tag '%s'", name)
		}
	}

	{ // With .imgpkg internal tags and digests
		out := imgpkg.Run([]string{"tag", "list", "--imgpkg-internal-tags", "-i", env.Image, "--digests=true", "--json"})
		resp := uitest.JSONUIFromBytes(t, []byte(out))

		for name, digest := range expectedTags {
			var found bool
			for _, row := range resp.Tables[0].Rows {
				if row["name"] == name {
					found = true
					require.Equal(t, digest, row["digest"])
					break
				}
			}
			require.Truef(t, found, "Expected to find tag '%s'", name)
		}
	}
}
